### PR TITLE
WIP: fix some tests

### PR DESCRIPTION
**Pull request by alfredmox**
I had issues building Zano on `Linux ubuntu 4.15.0-43-generic`, `gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)`.  
Some tests were causing the build to fail, here is my first attempt at fixing this.  
I don't expect this PR to be merged in it's current state and am mostly doing this for my own educational purpose.

### CODE REVIEW

**Comment by cryptozoidberg** [comment]
Hi @alfredmox! thanks for interest to the project, 29d8170 is fine, but about 256ab7d i say that having temporary variables in OPT_XOR_4_RES actually increase performance on my tests, i guess it due to caching memory lines. The rest looks fine, if you change it i would love to merge it.

**Comment by alfredmox** [comment]
My reasoning for removing temporary variables was the redefinition error when using `OPT_XOR_4_RES` twice in a row.
There must be a way around it, will change

**Comment by alfredmox** [comment]
e477762c14f2c43f1bbb10e81b95ebacb0cdf3ac should allow to use `OPT_XOR_4_RES` once per line without sacrificing the performances.  
`__LINE__` predefined macro allows that when being concatenated to the variable prefixed name

**Comment by cryptozoidberg** [comment]
Just to explain what happend here, the idea of this lines:
```
res_etalon = XOR_4(scratchpad_vec[0], scratchpad_vec[1], scratchpad_vec[2], scratchpad_vec[3]);
  OPT_XOR_4_RES(scratchpad_vec[0], scratchpad_vec[1], scratchpad_vec[2], scratchpad_vec[3], res_etalon);
```
was to compare that macro OPT_XOR_4_RES gives same result as XOR_4 (binary same result), but then i removed XOR_4 macro in 23b64c1 and worked on other things, and left this part broken. 
I kept this as a sandbox and didn't realize people is building all modules, thank you for fixing this!

**Pull request merged**
